=== AmanbekAzizUulu/java-networking-educational-project/src/main/resources/friends/properties/friends.dtd
<!ELEMENT friendList (friend+)>
<!ELEMENT friend (firstName, lastName, phoneNumber, dateOfBirth, address, email)>
<!ATTLIST friend id ID #REQUIRED>

<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT dateOfBirth (day, month, year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT address (street, building, apartment)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT apartment (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== AmanbekAzizUulu/java-networking-educational-project/src/main/resources/friends/repo/friends.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../properties/friends.xsl" type="text/xsl"?>

<!DOCTYPE friendList SYSTEM "../properties/friends.dtd">

<friendList>
	<friend id="uid001">
		<firstName>Aibek</firstName>
		<lastName>Dandaev</lastName>
		<phoneNumber>996555555555</phoneNumber>
		<dateOfBirth>
			<day>02</day>
			<month>October</month>
			<year>1998</year>
		</dateOfBirth>
		<address>
			<street>Chuy</street>
			<building>4k</building>
			<apartment>12</apartment>
		</address>
		<email>aibek.d@example.com</email>
	</friend>

	<friend id="uid002">
		<firstName>Aziz</firstName>
		<lastName>Uulu</lastName>
		<phoneNumber>996700123456</phoneNumber>
		<dateOfBirth>
			<day>15</day>
			<month>March</month>
			<year>2000</year>
		</dateOfBirth>
		<address>
			<street>Lenin</street>
			<building>7</building>
			<apartment>45</apartment>
		</address>
		<email>aziz.u@example.com</email>
	</friend>

	<friend id="uid003">
		<firstName>Alina</firstName>
		<lastName>Bekova</lastName>
		<phoneNumber>996555987654</phoneNumber>
		<dateOfBirth>
			<day>30</day>
			<month>December</month>
			<year>1995</year>
		</dateOfBirth>
		<address>
			<street>Manas</street>
			<building>12b</building>
			<apartment>3</apartment>
		</address>
		<email>alina.b@example.com</email>
	</friend>
	<friend id="uid004">
		<firstName>Aibek</firstName>
		<lastName>Dandaev</lastName>
		<phoneNumber>996555555555</phoneNumber>
		<dateOfBirth>
			<day>02</day>
			<month>October</month>
			<year>1998</year>
		</dateOfBirth>
		<address>
			<street>Chuy</street>
			<building>4k</building>
			<apartment>12</apartment>
		</address>
		<email>aibek.d@example.com</email>
	</friend>
	<friend id="uid005">
		<firstName>Aziz</firstName>
		<lastName>Uulu</lastName>
		<phoneNumber>996700123456</phoneNumber>
		<dateOfBirth>
			<day>15</day>
			<month>March</month>
			<year>2000</year>
		</dateOfBirth>
		<address>
			<street>Lenin</street>
			<building>7</building>
			<apartment>45</apartment>
		</address>
		<email>aziz.u@example.com</email>
	</friend>
	<friend id="uid006">
		<firstName>Alina</firstName>
		<lastName>Bekova</lastName>
		<phoneNumber>996555987654</phoneNumber>
		<dateOfBirth>
			<day>30</day>
			<month>December</month>
			<year>1995</year>
		</dateOfBirth>
		<address>
			<street>Manas</street>
			<building>12b</building>
			<apartment>3</apartment>
		</address>
		<email>alina.b@example.com</email>
	</friend>
	<friend id="uid007">
		<firstName>Meerim</firstName>
		<lastName>Asanova</lastName>
		<phoneNumber>996555234567</phoneNumber>
		<dateOfBirth>
			<day>22</day>
			<month>July</month>
			<year>1994</year>
		</dateOfBirth>
		<address>
			<street>Toktogul</street>
			<building>78</building>
			<apartment>5</apartment>
		</address>
		<email>meerim.a@example.com</email>
	</friend>
	<friend id="uid008">
		<firstName>Bakyt</firstName>
		<lastName>Jumaliev</lastName>
		<phoneNumber>996555345678</phoneNumber>
		<dateOfBirth>
			<day>08</day>
			<month>April</month>
			<year>1992</year>
		</dateOfBirth>
		<address>
			<street>Sovetskaya</street>
			<building>23</building>
			<apartment>9</apartment>
		</address>
		<email>bakyt.j@example.com</email>
	</friend>
	<friend id="uid009">
		<firstName>Gulnara</firstName>
		<lastName>Ismailova</lastName>
		<phoneNumber>996555456789</phoneNumber>
		<dateOfBirth>
			<day>14</day>
			<month>November</month>
			<year>1996</year>
		</dateOfBirth>
		<address>
			<street>Frunze</street>
			<building>56</building>
			<apartment>15</apartment>
		</address>
		<email>gulnara.i@example.com</email>
	</friend>
	<friend id="uid010">
		<firstName>Nurlan</firstName>
		<lastName>Osmonov</lastName>
		<phoneNumber>996555567890</phoneNumber>
		<dateOfBirth>
			<day>03</day>
			<month>September</month>
			<year>1991</year>
		</dateOfBirth>
		<address>
			<street>Ahunbaeva</street>
			<building>34</building>
			<apartment>7</apartment>
		</address>
		<email>nurlan.o@example.com</email>
	</friend>
	<friend id="uid011">
		<firstName>Aizada</firstName>
		<lastName>Ryskulova</lastName>
		<phoneNumber>996555678901</phoneNumber>
		<dateOfBirth>
			<day>19</day>
			<month>May</month>
			<year>1997</year>
		</dateOfBirth>
		<address>
			<street>Gorkiy</street>
			<building>89</building>
			<apartment>22</apartment>
		</address>
		<email>aizada.r@example.com</email>
	</friend>
	<friend id="uid012">
		<firstName>Ruslan</firstName>
		<lastName>Abdyev</lastName>
		<phoneNumber>996555789012</phoneNumber>
		<dateOfBirth>
			<day>25</day>
			<month>January</month>
			<year>1990</year>
		</dateOfBirth>
		<address>
			<street>Moskovskaya</street>
			<building>67</building>
			<apartment>18</apartment>
		</address>
		<email>ruslan.a@example.com</email>
	</friend>
	<friend id="uid013">
		<firstName>Madina</firstName>
		<lastName>Sultanova</lastName>
		<phoneNumber>996555890123</phoneNumber>
		<dateOfBirth>
			<day>11</day>
			<month>August</month>
			<year>1994</year>
		</dateOfBirth>
		<address>
			<street>Kievskaya</street>
			<building>14</building>
			<apartment>4</apartment>
		</address>
		<email>madina.s@example.com</email>
	</friend>
	<friend id="uid014">
		<firstName>Timur</firstName>
		<lastName>Bakirov</lastName>
		<phoneNumber>996555901234</phoneNumber>
		<dateOfBirth>
			<day>07</day>
			<month>October</month>
			<year>1993</year>
		</dateOfBirth>
		<address>
			<street>Lenina</street>
			<building>91</building>
			<apartment>11</apartment>
		</address>
		<email>timur.b@example.com</email>
	</friend>
	<friend id="uid015">
		<firstName>Cholpon</firstName>
		<lastName>Kadyrova</lastName>
		<phoneNumber>996555112233</phoneNumber>
		<dateOfBirth>
			<day>18</day>
			<month>February</month>
			<year>1999</year>
		</dateOfBirth>
		<address>
			<street>Pushkin</street>
			<building>25</building>
			<apartment>8</apartment>
		</address>
		<email>cholpon.k@example.com</email>
	</friend>
	<friend id="uid016">
		<firstName>Erbol</firstName>
		<lastName>Nazarov</lastName>
		<phoneNumber>996555223344</phoneNumber>
		<dateOfBirth>
			<day>29</day>
			<month>June</month>
			<year>1989</year>
		</dateOfBirth>
		<address>
			<street>Gagarin</street>
			<building>33</building>
			<apartment>14</apartment>
		</address>
		<email>erbol.n@example.com</email>
	</friend>
	<friend id="uid017">
		<firstName>Zarina</firstName>
		<lastName>Samatova</lastName>
		<phoneNumber>996555334455</phoneNumber>
		<dateOfBirth>
			<day>12</day>
			<month>December</month>
			<year>1997</year>
		</dateOfBirth>
		<address>
			<street>Bokonbaeva</street>
			<building>47</building>
			<apartment>6</apartment>
		</address>
		<email>zarina.s@example.com</email>
	</friend>
	<friend id="uid018">
		<firstName>Kanybek</firstName>
		<lastName>Toktogulov</lastName>
		<phoneNumber>996555445566</phoneNumber>
		<dateOfBirth>
			<day>05</day>
			<month>March</month>
			<year>1992</year>
		</dateOfBirth>
		<address>
			<street>Almatinskaya</street>
			<building>19</building>
			<apartment>21</apartment>
		</address>
		<email>kanybek.t@example.com</email>
	</friend>
	<friend id="uid019">
		<firstName>Dinara</firstName>
		<lastName>Ysmailova</lastName>
		<phoneNumber>996555556677</phoneNumber>
		<dateOfBirth>
			<day>23</day>
			<month>July</month>
			<year>1995</year>
		</dateOfBirth>
		<address>
			<street>Tynystanova</street>
			<building>8</building>
			<apartment>13</apartment>
		</address>
		<email>dinara.y@example.com</email>
	</friend>
	<friend id="uid020">
		<firstName>Sanjar</firstName>
		<lastName>Rakhmanov</lastName>
		<phoneNumber>996555667788</phoneNumber>
		<dateOfBirth>
			<day>31</day>
			<month>January</month>
			<year>1991</year>
		</dateOfBirth>
		<address>
			<street>Isanova</street>
			<building>52</building>
			<apartment>17</apartment>
		</address>
		<email>sanjar.r@example.com</email>
	</friend>
	<friend id="uid021">
		<firstName>Ainura</firstName>
		<lastName>Shukurova</lastName>
		<phoneNumber>996555778899</phoneNumber>
		<dateOfBirth>
			<day>09</day>
			<month>April</month>
			<year>1998</year>
		</dateOfBirth>
		<address>
			<street>Baytik</street>
			<building>41</building>
			<apartment>10</apartment>
		</address>
		<email>ainura.s@example.com</email>
	</friend>
	<friend id="uid022">
		<firstName>Maksat</firstName>
		<lastName>Kalenov</lastName>
		<phoneNumber>996555889900</phoneNumber>
		<dateOfBirth>
			<day>27</day>
			<month>November</month>
			<year>1993</year>
		</dateOfBirth>
		<address>
			<street>JibekJolu</street>
			<building>63</building>
			<apartment>16</apartment>
		</address>
		<email>maksat.k@example.com</email>
	</friend>
	<friend id="uid023">
		<firstName>Elmira</firstName>
		<lastName>Batyrbekova</lastName>
		<phoneNumber>996555990011</phoneNumber>
		<dateOfBirth>
			<day>14</day>
			<month>August</month>
			<year>1996</year>
		</dateOfBirth>
		<address>
			<street>Salieva</street>
			<building>29</building>
			<apartment>19</apartment>
		</address>
		<email>elmira.b@example.com</email>
	</friend>

	<friend id="uid024">
		<firstName>Aibek</firstName>
		<lastName>Khan</lastName>
		<phoneNumber>996555123456</phoneNumber>
		<dateOfBirth>
			<day>15</day>
			<month>March</month>
			<year>1993</year>
		</dateOfBirth>
		<address>
			<street>Chui</street>
			<building>45</building>
			<apartment>12</apartment>
		</address>
		<email>aibek.khan@example.com</email>
	</friend>
	<friend id="uid025">
		<firstName>Meerim</firstName>
		<lastName>Asanova</lastName>
		<phoneNumber>996555234567</phoneNumber>
		<dateOfBirth>
			<day>22</day>
			<month>July</month>
			<year>1994</year>
		</dateOfBirth>
		<address>
			<street>Toktogul</street>
			<building>78</building>
			<apartment>5</apartment>
		</address>
		<email>meerim.a@example.com</email>
	</friend>
	<friend id="uid026">
		<firstName>Alina</firstName>
		<lastName>Bekova</lastName>
		<phoneNumber>996555987654</phoneNumber>
		<dateOfBirth>
			<day>30</day>
			<month>December</month>
			<year>1995</year>
		</dateOfBirth>
		<address>
			<street>Manas</street>
			<building>12b</building>
